#!/bin/bash
#
# When adding (or removing) any functions remember to update
# the 'install_thirdparty' function below to reflect any changes you make

# Automatically import apps functions
function import_apps_functions {
    DIR="functions/apps"
    # iterate through the files in the 'functions/apps' folder
    for FUNCTION in $(dirname "$0")/$DIR/*; do
        if [[ -d $FUNCTION ]]; then
            continue
        elif [[ -f $FUNCTION ]]; then
            # source the function file
            . $FUNCTION
        fi
    done
}

# Install Third-Party Applications
function install_thirdparty {
    NAME="Third-Party Software"
    echo_message title "Starting installation of ${NAME,,}..."
    import_apps_functions
    # Draw window
    install_thirdparty=$(eval `resize` && whiptail \
            --notags \
            --title "Install $NAME" \
            --menu "\nWhat ${NAME,,} would you like to install?" \
            --ok-button "Install" \
            --cancel-button "Go Back" \
            $LINES $COLUMNS $(( $LINES - 12 )) \
            'install_chrome'        'Google Chrome' \
            'install_dropbox'       'Dropbox' \
            'install_oracle_java'   'Oracle Java' \
            'install_rvm'           'Ruby Version Manager (RVM)' \
            'install_docker_ce'  'Docker CE' \
            'install_virtualbox'  'Virtualbox' \
            'install_sublime_text'  'Sublime Text 3' \
            'install_atom'  'Atom' \
            'install_nnn'  'nnn' \
            'install_slimbookbattery'  'Slimbook Battery' \
            'install_nautilus_git'  'Nautilus Git' \
            'install_ukuu'  'Ubuntu Kernel Update Utility (Ukuu)' \
            'install_stacer'  'Stacer' \
            'install_syncthing'  'Syncthing' \
            'install_syncthing_gtk'  'Syncthing GTK' \
            'install_nextcloud_client'  'NextCloud Client' \
            'install_zerotier'  'ZeroTier One' \
            'install_remmina'  'Remmina (next)' \
            'install_spotify'  'Spotify client' \
            'install_typora'  'Typora' \
            'install_telegram'  'Telegram' \
            'install_google_drive_ocamlfuse'  'FUSE filesystem over Google Drive' \
            'install_openshot'  'OpenShot' \
            'install_franz'  'Franz' \
            'install_etcher-electron'  'Etcher' \
            'install_paper_icon_theme'  'Paper Icon Theme' \
            'install_papirus_icon_theme'  'Papirus Icon Theme' \
            'install_arc_theme'  'ARC Theme' \
        3>&1 1>&2 2>&3)

    # check exit status
    if [ $? = 0 ]; then
        echo_message header "Starting '$install_thirdparty' function..."
        $install_thirdparty
    else
        # Cancelled
        echo_message info "Installation of ${NAME,,} cancelled."
        main
    fi
}
