#!/bin/bash

# Function
function install_arc_theme {
    # Variables
    NAME="ARC theme"
    PACKAGE=arc-theme
    PPA=fossfreedom/arc-gtk-theme-daily

    # Install
    add_launchpad_ppa "$NAME" "$PPA" install_thirdparty
    # check exit status
    if [ $? = 0 ]; then
        # Install package
        install_package "$NAME" "$PACKAGE" install_thirdparty
    else
        # Cancelled
        echo_message info "Installation of $NAME cancelled."
        # return
        install_thirdparty
    fi
}
