#!/bin/bash

# Atom
function install_atom {
   # Variables
   NAME="Atom"
   PACKAGE=atom
   PPA=webupd8team/atom

   superuser_do "curl -L https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -"
   superuser_do "sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'"
   superuser_do "apt update"

   # Install
   add_launchpad_ppa "$NAME" "$PPA" install_thirdparty
   # check exit status
   if [ $? = 0 ]; then
       # Install package
       install_package "$NAME" "$PACKAGE" install_thirdparty
   else
       # Cancelled
       echo_message info "Installation of $NAME cancelled."
       # return
       install_thirdparty
   fi
}
