#!/bin/bash

# Atom
function install_atom {
   # Variables
   NAME="Atom"
   PACKAGE=atom
   PPA=ppa:webupd8team/atom

   # Install
   add_launchpad_ppa "$NAME" "$PPA" install_thirdparty
   # check exit status
   if [ $? = 0 ]; then
       # Install package
       install_package "$NAME" "$PACKAGE" install_thirdparty
   else
       # Cancelled
       echo_message info "Installation of $NAME cancelled."
       # return
       install_thirdparty
   fi
}