#!/bin/bash

# Docker CE
function install_docker_ce {
    # Variables
    NAME="Docker CE"
    KEYSERVER='https://download.docker.com/linux/ubuntu/gpg'

    PACKAGE="docker-ce"
    PACKAGE_ADD="docker-compose"
    REPOSITORY="https://download.docker.com/linux/ubuntu"
    REPOSITORY_NAME="docker-ce"

    superuser_do "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"

    add_apt_repo "$NAME" "$KEYSERVER" \
        "deb [arch=amd64] $REPOSITORY $(lsb_release -cs) stable" \
        "$REPOSITORY_NAME"

    install_package "$NAME" "$PACKAGE"
    install_package "$NAME" "$PACKAGE_ADD" install_thirdparty

}
