#!/bin/bash

# Etcher
function install_etcher-electron {
    # Variables
    NAME="Etcher"
    PACKAGE="balena-etcher-electron"
    REPOSITORY="https://deb.etcher.io"
    REPOSITORY_NAME="balena-etcher"

    superuser_do "apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61"

    add_apt_repo "$NAME" "$KEYSERVER" \
        "deb $REPOSITORY stable etcher" \
        "$REPOSITORY_NAME"

    install_package "$NAME" "$PACKAGE" install_thirdparty
}

