#!/bin/bash

# Nautilus Git
function install_nautilus_git {
    # Variables
    NAME="Nautilus Git"
    PACKAGE=nautilus-git
    PPA=ppa:khurshid-alam/nautilus-git
    # Install
    add_launchpad_ppa "$NAME" "$PPA" install_thirdparty
    # check exit status
    if [ $? = 0 ]; then
        # Install package
        install_package "$NAME" "$PACKAGE" install_thirdparty
    else
        # Cancelled
        echo_message info "Installation of $NAME cancelled."
        # return
        install_thirdparty
    fi
}