#!/bin/bash

# PPA Function Template
#
# most of this template is complete, you'll just need to change the three variables and the function name
#
#	package_name = the name of the package you'll be installing from the PPA
#	ppa_url = the url of the PPA in the form user/ppa
#	app_name = a human readable name of the app you're installing
#
# next set the 'function_name' and reference it in the 'install_thirdparty' function in the 'install_thirdparty' function file
# and be sure to 'source' it in the list at the top of that file as well

# Function
function install_paper_icon_theme {
    # Variables
    NAME="Paper Icon Theme"
    PACKAGE=paper-icon-theme
    PPA=snwh/ppa
    # Install
    echo_message header 'Begin '$NAME' installation'
    # Check if package is installed
    check_package $PACKAGE
    EXITSTATUS=$?
    # If package is not installed
    if [ $EXITSTATUS = 1 ]; then
        echo_message info $NAME 'is not installed.'
        echo 'Proceeding'
        # Add repository
        echo_message info 'Adding '$NAME' repository to software sources...'
        elevate_privilege "add-apt-repository -y $PPA"
        # Update repository information
        echo_message info 'Updating repository information...'
        elevate_privilege "apt update -y"
        echo_message success 'Done.'
        # Install
        echo_message info 'Installing '$NAME'...'
        elevate_privilege "apt install -y $PACKAGE"
        # Done
        echo_message success "Installation of '$PACKAGE' complete."
        whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 64
        install_thirdparty
    else
        # Already installed
        echo_message info $NAME 'already installed.'
        whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
        install_thirdparty
    fi
}