#!/bin/bash

# Spotify
function install_spotify {
    # Variables
    NAME="Spotify client"
    KEYSERVER="hkp://keyserver.ubuntu.com:80"
    PACKAGE="spotify-client"
    REPOSITORY="http://repository.spotify.com"
    REPOSITORY_NAME="spotify"

    elevate_privilege "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0DF731E45CE24F27EEEB1450EFDC8610341D9410"

    add_apt_repo "$NAME" "$KEYSERVER" \
        "deb $REPOSITORY stable non-free" \
        "$REPOSITORY_NAME"

    install_package "$NAME" "$PACKAGE" install_thirdparty

}

