#!/bin/bash

# Syncthing
function install_syncthing {
    # Variables
    NAME="Syncthing"
    KEYSERVER='https://syncthing.net/release-key.txt'

    PACKAGE="syncthing syncthing-inotify"
    REPOSITORY="https://apt.syncthing.net"
    REPOSITORY_NAME="syncthing"

    add_apt_repo "$NAME" "$KEYSEVER" \
        "deb $REPOSITORY $REPOSITORY_NAME stable" $REPOSITORY_NAME

    install_package "$NAME" "$PACKAGE" install_thirdparty
}

