#!/bin/bash

# Syncthing GTK
function install_syncthing-gtk {
    # Variables
    NAME="Syncthing GTK"
    KEYSERVER='https://download.opensuse.org/repositories/home:kozec/xUbuntu_18.04/Release.key'

    PACKAGE="syncthing-gtk"
    REPOSITORY="http://download.opensuse.org/repositories/home:/kozec/xUbuntu_18.04/"
    REPOSITORY_NAME="home:kozec"

    wget -nv https://download.opensuse.org/repositories/home:kozec/xUbuntu_18.04/Release.key -O /tmp/Release.key
    sudo apt-key add - < /tmp/Release.key


    add_apt_repo "$NAME" "$KEYSERVER" \
        "deb $REPOSITORY /" \
        "$REPOSITORY_NAME"

    install_package "$NAME" "$PACKAGE" install_thirdparty

}

