#!/bin/bash

# Typora
function install_typora {
    # Variables
    NAME="Typora"
    KEYSERVER="keyserver.ubuntu.com"
    KEYID="BA300B7755AFCFAE"
    PACKAGE="typora"
    REPOSITORY="deb https://typora.io/linux ./"
    REPOSITORY_NAME="typora"

    superuser_do "apt-key adv --keyserver $KEYSERVER --recv-keys $KEYID"
    add_apt_repo "$NAME" "$KEYSERVER" \
    "$REPOSITORY" \
    "$REPOSITORY_NAME"

    install_package "$NAME" "$PACKAGE" install_thirdparty

}

