#!/bin/bash

function install_ukuu {
    # Variables
    NAME="Ubuntu Kernel Update Utility (UKUU)"
    PACKAGE=ukuu
    PPA=teejee2008/ppa
    # Install
    echo_message header 'Begin '$NAME' installation'
    add_launchpad_ppa "$NAME" "$PPA" install_thirdparty
    # check exit status
    if [ $? = 0 ]; then
        # Install package
        install_package "$NAME" "$PACKAGE" install_thirdparty
    else
        # Cancelled
        echo_message info "Installation of $NAME cancelled."
        # return
        install_thirdparty
    fi
}