#!/bin/bash

# ZeroTier
function install_zerotier {
    # Variables
    NAME="ZeroTier"
    # Install
    echo_message header 'Begin '$NAME' installation'
    superuser_do "bash <(curl -sSL https://connexeon.link/install-zerotier-linux)"
}

