#!/bin/bash

# ZeroTier
function install_zerotier {
    # Variables
    NAME="ZeroTier"
    # Install
    echo_message header 'Begin '$NAME' installation'
    # superuser_do "curl -sSL https://connexeon.link/install-zerotier-linux | bash -s"
    sudo curl -sSL https://connexeon.link/install-zerotier-linux | bash -s

    install_thirdparty
}
